# 数组方法

In [1]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## 求和

In [2]:
a = array([[1,2,3], 
           [4,5,6]])

求所有元素的和：

In [3]:
sum(a)

21

指定求和的维度：

沿着第一维求和：

In [4]:
sum(a, axis=0) # 行与行之间的操作，从另一个角度来理解就是做了竖向操作；

array([5, 7, 9])

沿着第二维求和：

In [5]:
sum(a, axis=1) # 列与列之间操作，从另一个角度来理解就是做了横向操作；

array([ 6, 15])

沿着最后一维求和：

In [6]:
sum(a, axis=-1)

array([ 6, 15])

或者使用 `sum` 方法：

In [7]:
a.sum()

21

In [8]:
a.sum(axis=0)

array([5, 7, 9])

In [9]:
a.sum(axis=-1)

array([ 6, 15])

## 求积

求所有元素的乘积：

In [10]:
a.prod()

720

或者使用函数形式：

In [11]:
prod(a, axis=0)

array([ 4, 10, 18])

## 求最大最小值

In [5]:
from numpy.random import rand  #这个rand也是numpy库的
a = rand(3, 4)
%precision 3
a

array([[0.573, 0.095, 0.137, 0.135],
       [0.585, 0.123, 0.908, 0.131],
       [0.386, 0.943, 0.23 , 0.664]])

In [6]:
1.33333333 # 上面设置了全局数值精度

1.333

全局最小：

In [7]:
a.min()

0.09453549167691588

沿着某个轴的最小：

In [8]:
a.min(axis=0) # 竖向作对比，得到一行（元素个数与列数一致）

array([0.386, 0.095, 0.137, 0.131])

In [9]:
a.min(axis=1)  # 横向做对比，元素个数与行数一致；

array([0.095, 0.123, 0.23 ])

全局最大：

In [15]:
a.max()

0.810

沿着某个轴的最大：

In [8]:
a.max(axis=-1)

array([0.966, 0.673, 0.852])

In [9]:
a.max(axis=1) # 发现-1 和 1是相等的，这个应该是在二维数组的时候

array([0.966, 0.673, 0.852])

## 最大最小值的位置

使用 `argmin, argmax` 方法：

In [6]:
a.argmin()

4

In [7]:
a.argmin(axis=0)

array([1, 0, 1, 2])

## 均值

可以使用 `mean` 方法：

In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

In [12]:
a.mean()

3.5

In [21]:
a.mean(axis=-1)

array([ 2.,  5.])

也可以使用 `mean` 函数：

In [22]:
mean(a)

3.500

In [14]:
# mean 能不能加权？-- 可以看到mean方法不可以加权，但是average方法是可以的；
np.mean(a, axis=0, weight=[1,2])

TypeError: _mean_dispatcher() got an unexpected keyword argument 'weight'

还可以使用 `average` 函数：

In [20]:
np.average(a, axis = -1) # # 如果不加权重，结果和mean一致；

array([2., 5.])

`average` 函数还支持加权平均：

In [24]:
average(a, axis = 0, weights=[1,2])

array([ 3.,  4.,  5.])

## 标准差

用 `std` 方法计算标准差：

In [25]:
a.std(axis=1)

array([ 0.816,  0.816])

用 `var` 方法计算方差：

In [26]:
a.var(axis=1)

array([ 0.667,  0.667])

或者使用函数：

In [27]:
var(a, axis=1)

array([ 0.667,  0.667])

In [28]:
std(a, axis=1)

array([ 0.816,  0.816])

## clip 方法

将数值限制在某个范围：

In [2]:
a

array([[0.079, 0.168, 0.696, 0.789],
       [0.368, 0.637, 0.726, 0.966],
       [0.015, 0.525, 0.683, 0.691]])

In [3]:
a.clip(3,5)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

小于3的变成3，大于5的变成5。

In [ ]:
# matao：神奇，且很少用到；
# 一般应该在后处理的时候会用到；

## ptp 方法

计算最大值和最小值之差：

In [4]:
a.ptp(axis=1) # axis=1 进行列操作

array([0.71 , 0.598, 0.676])

In [32]:
a.ptp()

5

## round 方法

近似，默认到整数：

In [33]:
a = array([1.35, 2.5, 1.5])

这里，.5的近似规则为近似到偶数值，可以参考：

https://en.wikipedia.org/wiki/Rounding#Round_half_to_odd

In [34]:
a.round()

array([ 1.,  2.,  2.])

近似到一位小数：

In [35]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])