# 数组与字符串的转换

## tostring 方法

In [10]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [2]:
a = np.array([[1,2],
           [3,4]], 
          dtype = np.uint8)

In [3]:
# cc
a.tostring() # 发现python3中 tostring() 已经过时，推荐使用 tobytes()

<ipython-input-3-482fe6683670>:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  a.tostring() # 发现python3中 tostring() 已经过时，推荐使用 tobytes()


b'\x01\x02\x03\x04'

In [4]:
# cc
a.tobytes()

b'\x01\x02\x03\x04'

转化为字符串：

我们可以使用不同的顺序来转换字符串：

In [9]:
a.tobytes(order='F')

b'\x01\x03\x02\x04'

这里使用了**Fortran**的格式，按照列来读数据。

## fromstring 函数

可以使用 `fromstring` 函数从字符串中读出数据，不过要指定类型：

In [15]:
s = a.tobytes()
s

# fromstring 已经被弃用了，可以改用 frombuffer
a = np.fromstring(s, 
                  dtype=np.uint8)
a

a = np.frombuffer(s, 
                  dtype=np.uint8)
a

b'\x01\x02\x03\x04'

<ipython-input-15-5b14713b8a2c>:3: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  a = np.fromstring(s,


array([1, 2, 3, 4], dtype=uint8)

array([1, 2, 3, 4], dtype=uint8)

此时，返回的数组是一维的，需要重新设定维度：

In [6]:
a.shape = 2,2
a

array([[1, 2],
       [3, 4]], dtype=uint8)

对于文本文件，推荐使用
- `loadtxt`
- `genfromtxt`
- `savetxt`

对于二进制文本文件，推荐使用 
- `save` 
- `load`
- `savez`