# 矩阵

In [7]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


使用 `mat` 方法将 `2` 维数组转化为矩阵：

In [2]:
import numpy as np
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A


matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [ ]:
# cc: 可以看到上面类型变成了matrix 矩阵
# 但是这里抛出一个问题：matrix（矩阵）和 二维array（数组）的区别 --- matrix就有更多矩阵计算的方法

也可以使用 **Matlab** 的语法传入一个字符串来生成矩阵：

In [2]:
A = np.mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

利用分块创造新的矩阵：

In [3]:
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

# 通过数组的拼接构建出了矩阵；

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

矩阵与向量的乘法：

In [4]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [8]:
A * x # A的每一行，乘x

# cc：如果直接用数组来实现，应该要用“点积”方式，且得到的还是array
np.dot(a, x)


matrix([[17],
        [21],
        [50]])

array([[17],
       [21],
       [50]])

In [5]:
# 如果把A替换成数组，按照上面方式得到的结果如下：

a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
a * x
# 也就是每一列乘x对应位置的元素


array([[ 1,  2,  4],
       [ 4, 10,  6],
       [21, 24, 27]])

`A.I` 表示 `A` 矩阵的逆矩阵：

In [6]:
print A * A.I

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   2.08166817e-17]
 [  2.22044605e-16  -8.32667268e-17   1.00000000e+00]]


矩阵指数表示矩阵连乘：

In [7]:
print A ** 4

[[ 6497  9580  9836]
 [ 7138 10561 10818]
 [18434 27220 27945]]
